### ISSUE TITLE
base bound too low

### ISSUE THREAD

**Issue by ocharles** [muesli4/table-layout#1]
Could your base upper bound be increased? `4.11` is out now.

**Comment by muesli4** [comment]
I will publish an update in a moment. I will still keep an upper bound. Is this the preferred way?

**Comment by ocharles** [comment]
Hi, yes you need an upper bound. However it turns out you're not actually
compatible with GHC 8.4  , so I wouldn't release a new version until those
problems are fixed.

**Comment by muesli4** [comment]
I've compiled and tested with GHC 8.4.3 and it seems to work. (I added `Semigroup` instances.)

**Comment by ocharles** [comment]
Ah, perfect! It was those missing instances I hit
