### ISSUE TITLE
Update version bounds on QuickCheck

### ISSUE THREAD

**Issue by sternenseemann** [muesli4/table-layout#16]
table-layout works with QuickCheck 2.14.2, but its bounds forbid it.

**Comment by muesli4** [comment]
Feel free to submit a patch.  I wouldn't categorize it as something very important and don't have a lot of time at the moment.  Unless you see a good reason to increase them.

**Comment by sternenseemann** [comment]
A new release / hackage cabal file revision would be useful.

**Comment by muesli4** [comment]
Sorry for the inconvenience.  I will try to do it as soon as possible.  There is still stuff from another merge request that I want to have in the release but the review is a little bit bigger.
