### ISSUE TITLE
Allow Strings in TableStyle

### ISSUE THREAD

**Issue by Xitian9** [muesli4/table-layout#17]
Currently `TableStyle` allows only a single character for the various separators. Occasionally you may want to allow more flexibility: for example, you may want a double-thick line in ASCII for vertical separators`||`, or you may wish to exclude the outer border of a table entirely.

Would you be open to a PR to enable this functionality?

**Comment by muesli4** [comment]
Yes, your contribution would be very welcome.  Although, when it comes to any design questions I would like to be involved.   Let me know if there is anything you need.

**Comment by Xitian9** [comment]
I've submitted a couple of PRs addressing this and other issues. I don't mean this to be an end-run around design questions, but just so we have something concrete to look at when discussing any issues. Let me know what you think.
