### ISSUE TITLE
Check for superfluous imports in Text.Layout.Table module

### ISSUE THREAD

**Issue by muesli4** [muesli4/table-layout#50]
Check whether some imports are unlikely to be used by the typical user.  As potential candidates I would suggest:
- `zipHeader`
- `flattenHeader`
- `headerContents`
- Column modification functions
- Column modification primitives

It seems that if someone really wants to go that deep they should actually import specific modules.

**Comment by muesli4** [comment]
@Xitian9, may I ask about your opinion on those?

**Comment by Xitian9** [comment]
So long as they're available to import directly from the module, that sounds reasonable to me.

**Comment by muesli4** [comment]
I noticed that restructuring the documentation cleared up the situation mostly.  Moving more advanced definitions into a section that is at the end may be sufficient.

**Comment by Xitian9** [comment]
That sounds reasonable to me.
